name: mlr-project
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - aiofile==3.9.0
      - aiofiles==24.1.0
      - argcomplete==3.6.2
      - argparse==1.4.0
      - boto3==1.37.38
      - botocore==1.37.38
      - bracex==2.5.post1
      - cachetools==5.5.2
      - caio==0.9.22
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - clarabel==0.9.0
      - cloudpickle==1.3.0
      - contourpy==1.1.1
      - cvxpy==1.5.2
      - cycler==0.12.1
      - cython==3.1.2
      - dill==0.4.0
      - ecos==2.0.14
      - etils==1.3.0
      - expandvars==1.0.0
      - fasteners==0.19
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - functional-notations==0.5.2
      - future==1.0.0
      - glfw==2.9.0
      - google-api-core==2.25.1
      - google-api-python-client==2.175.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.2.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - graphql-server-core==1.1.1
      - grpcio==1.70.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - h11==0.9.0
      - h5py==3.11.0
      - httpcore==0.11.1
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.15.4
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jaynes==0.9.11
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lcm==1.5.1
      - lxml==6.0.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - ml-dash==0.3.20
      - ml-logger==0.8.117
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - mujoco==3.2.0
      - mujoco-py==2.1.2.14
      - multidict==4.6.1
      - networkx==3.1
      - ninja==1.11.1.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - onnx==1.15.0
      - opencv-python==4.5.5.64
      - osqp==1.0.4
      - packaging==25.0
      - pandas==2.0.3
      - params-proto==2.10.5
      - pillow==10.4.0
      - promise==2.3
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybullet==3.2.1
      - pycparser==2.22
      - pycurl==7.45.6
      - pygame==2.6.1
      - pyglet==1.3.2
      - pyopengl==3.1.9
      - pyparsing==3.1.4
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - requests==2.32.4
      - requests-futures==1.0.2
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3986==1.5.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.11.5
      - sanic==20.9.0
      - sanic-cors==0.10.0.post3
      - sanic-graphql==1.1.0
      - sanic-plugins-framework==0.9.5
      - sanic-routing==22.3.0
      - scikit-image==0.21.0
      - scikit-video==1.1.11
      - scipy==1.10.1
      - scs==3.2.7.post2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.3
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - torch==2.1.2+cu121
      - torchaudio==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - tqdm==4.67.1
      - transformations==2022.9.26
      - triton==2.1.0
      - typing==3.7.4.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - ujson==5.10.0
      - uritemplate==4.1.1
      - urllib3==1.26.20
      - uvloop==0.21.0
      - waterbear==2.6.8
      - wcmatch==10.0
      - websockets==8.1
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /home/kubuser/anaconda3/envs/mlr-project
